### ISSUE TITLE
『叨扰』

### ISSUE THREAD

**Issue by alaskasquirrel** [chasays/newsletter-list#11]
[Chinese-Podcasts](https://github.com/alaskasquirrel/Chinese-Podcasts)&[Email-newsletter-RSS](https://github.com/alaskasquirrel/Email-newsletter-RSS) 虽说关注者不少，但参与者屈指可数，长期更新都是我自己。能否通过你的项目分享呼吁一下。

**Comment by chasays** [comment]
> [Chinese-Podcasts](https://github.com/alaskasquirrel/Chinese-Podcasts)&[Email-newsletter-RSS](https://github.com/alaskasquirrel/Email-newsletter-RSS) 虽说关注者不少，但参与者屈指可数，长期更新都是我自己。能否通过你的项目分享呼吁一下。

你这个关注人气可比这list高多了吧😂
也非常的全面，有rss和Newsletter，以及podcast，我放到一个里面吧~ 
太多了估计引起焦虑，哈哈😜
