### ISSUE TITLE
HelloGitHub

### ISSUE THREAD

**Issue by mjTree** [chasays/newsletter-list#12]
https://hellogithub.com/
编程技术，月刊

**Comment by hiDaDeng** [comment]
编程技术, https://hidadeng.github.io/

**Comment by chasays** [comment]
> 

感谢推荐。

真奇妙，发现很早就关注你的公号了，感谢你的分享。
这个list主要是针对的Newsletter类的，如果是博客类的，暂时没有收录，谢谢。
